#pragma once

#define DYNAMIC_KEYMAP_LAYER_COUNT 4
#define TAPPING_TERM 175
#define HOLD_ON_OTHER_KEY_PRESS_PER_KEY
#define CAPS_WORD_IDLE_TIMEOUT 4000

#define COMBO_TERM 30
#define EXTRA_SHORT_COMBOS
#define COMBO_TERM_PER_COMBO
#define COMBO_MUST_TAP_PER_COMBO
#define COMBO_SHOULD_TRIGGER
#define COMBO_STRICT_TIMER
