#pragma once

#define DYNAMIC_KEYMAP_LAYER_COUNT 4
#define TAPPING_TERM 175
#define TAPPING_TERM_PER_KEY
#define QUICK_TAP_TERM_PER_KEY
#define HOLD_ON_OTHER_KEY_PRESS_PER_KEY
#define BOTH_SHIFTS_TURNS_ON_CAPS_WORD
#define CAPS_WORD_IDLE_TIMEOUT 4000
#define RGB_MATRIX_SLEEP
// Sync layer/Caps Word/combo indicator state to the slave half for RGB.
#define SPLIT_TRANSACTION_IDS_USER RPC_ID_USER_INDICATOR_SYNC

#define COMBO_TERM 30
#define EXTRA_SHORT_COMBOS
#define COMBO_TERM_PER_COMBO
#define COMBO_MUST_TAP_PER_COMBO
#define COMBO_SHOULD_TRIGGER
#define COMBO_STRICT_TIMER
